### ISSUE TITLE
How to use Webp-UIImage in swfit Project 

### ISSUE THREAD

**Issue by qingpengchen2011** [shmidt/WebP-UIImage#2]
Hello, I drag the framework and class folder to my swift project.
The project builds well.
But when my app is to launch in the simulator, error occurs saying: The operation couldn't be completed.
(LaunchServicesError error 0)
What can I do to fix this ?
Thanks.

**Comment by shmidt** [comment]
Sorry for the late answer. 
I don't know because I decided not to use WebP, as it is very slow on encoding images on iOS devices (there is no hardware support).
You can try to use this repo https://github.com/seanooi/iOS-WebP and bridging header.
